### ISSUE TITLE
Error: ORA-01461: can bind a LONG value only for insert into a LONG column

### ISSUE THREAD

**Issue by alfaz151** [Credence-Analytics/winston-oracle#6]
Encountering an error when attempting to log a string with a length exceeding 30,000 characters. The error message received is as follows:
Error: ORA-01461: can bind a LONG value only for insert into a LONG column
    at async @credenceanalytics\winston-oracle\index.js:67:17 {
  errorNum: 1461,
  offset: 12
}
2023-06-06 12:53:50 [request-id:15492200-043b-11ee-9b07-e9362d381ac4]: error: uncaughtException: ORA-01461: can bind a LONG value only for insert into a LONG column
Error: ORA-01461: can bind a LONG value only for insert into a LONG column
    at async C:\credence\microservices\NRest\node_modules\@credenceanalytics\winston-oracle\index.js:67:17
2023-06-06 12:53:50 [request-id:15492200-043b-11ee-9b07-e9362d381ac4]: error: uncaughtException: ORA-01461: can bind a LONG value only for insert into a LONG column

**Comment by shubham-credence** [comment]
This issue is resolved in version 1.0.3
